### PR TITLE
txt parsing, more verbose errors for XML parsing, reformatting

### PR DESCRIPTION
**Pull request by Naphier**
- Added ability to parse txt file format sometimes used by Kenney (format: <sprite_name> = <x> <y> <w> <h>).
- Added more verbose error checking to XML parsing after finding an XML file with the word "width" mispelled.
- Reformatted to C# conventions (VS just did it automatically).

### CODE REVIEW

**Comment by toxicFork** [comment]
Thanks for the PR! :D

**Comment by JacobMillward** [comment]
This still hasn't been merged, someone fancy getting on it?

**Comment by toxicFork** [comment]
Sorry! I'm back on being active on my open source projects now, so adding
it back into my to-do list to merge it :)

**Comment by toxicFork** [comment]
1+ year later...

**Comment by Naphier** [comment]
Ha! Well at least it got done!

**Pull request merged**
